version: "3"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports: 
      - 3003:3000
    volumes: 
      - .:/app
    depends_on:
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    container_name: database
    environment:
      - MYSQL_DATABASE=my_database
      - MYSQL_ROOT_PASSWORD=password
